package com.peekpick.stock.domain.model;

public enum StockAnalysisFormat {
    STOCK_MARKET_HTML(
            """
                            <!DOCTYPE html>
                            <html lang="en">
                            <head>
                                <meta charset="UTF-8">
                                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                <title>Stock Analysis - PeekPick</title>
                                <style>
                                    body { font-family: Arial, sans-serif; padding: 20px; background-color: #f4f4f4; }
                                    .container { background: white; padding: 20px; border-radius: 8px; max-width: 600px; margin: 0 auto; }
                                    .page { margin-bottom: 20px; }
                                    .controls { text-align: center; margin-top: 20px; }
                                    button { margin: 0 5px; padding: 5px 10px; }
                                    .footer { margin-top: 30px; text-align: center; color: #777; font-size: 12px; }
                                </style>
                                <script>
                                    let currentPage = 0;
                                    function showPage(index) {
                                        const pages = document.querySelectorAll('.page');
                                        pages.forEach((p, i) => {
                                            p.style.display = i === index ? 'block' : 'none';
                                        });
                                        currentPage = index;
                                    }
                                    function nextPage() {
                                        const pages = document.querySelectorAll('.page');
                                        if (currentPage < pages.length - 1) showPage(currentPage + 1);
                                    }
                                    function prevPage() {
                                        if (currentPage > 0) showPage(currentPage - 1);
                                    }
                                </script>
                            </head>
                            <body>
                                <div class="container">
                                    <h1>Stock Analysis Report</h1>
                                    %s
                                    <div class="controls">
                                        <button onclick="prevPage()">Previous</button>
                                        <button onclick="nextPage()">Next</button>
                                    </div>
                                    <div class="footer">
                                        <p>Generated by PeekPick &copy; 2025</p>
                                    </div>
                                </div>
                            </body>
                            </html>
                    """
    );

    private final String template;

    StockAnalysisFormat(String template) {
        this.template = template;
    }

    public String template() {
        return template;
    }
}
